### ISSUE TITLE
加载大众点评xml之后都出现错误

### ISSUE THREAD

**Issue by CapitaineNemo** [ferventdesert/Hawk-Projects#2]
该操作执行失败，错误信息，‘>’ is an unexpected token. The expected token is '=' line 42,position 92.

**Comment by byenic** [comment]
@CapitaineNemo 遇到同样问题，求问怎么解决

**Comment by ferventdesert** [comment]
这个是解析xml出现了错误，可能xml已经被修改？
不过这个xml价值已经不大了，因为大众点评改版，hawk也有一些改进，很可能是无法直接用起来的。建议直接创建新方案。
最近会发布hawk3，也会提供一部分常见网站的爬虫工程
